spring:
  application:
    name: helloconsumer
server:
  port: '7211'
provider:
  ribbon:
    NIWSServerListClassName: org.apache.servicecomb.springboot.starter.discovery.ServiceCombServerList
pojoService:
  ribbon:
    NIWSServerListClassName: org.apache.servicecomb.springboot.starter.discovery.ServiceCombServerList
eureka:
  instance:
    leaseRenewalIntervalInSeconds: '10'
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/
endpoints:
  restart:
    enabled: 'true'
  health:
    sensitive: 'false'
  shutdown:
    enabled: 'true'
cse:
  service:
    registry:
      address: http://127.0.0.1:30100
