spring:
  application:
    name: helloconsumer
server:
  port: '7211'
endpoints:
  restart:
    enabled: 'true'
  health:
    sensitive: 'false'
  shutdown:
    enabled: 'true'
cse:
  helloprovider:
    ribbon:
      NIWSServerListClassName: org.apache.servicecomb.springboot.starter.discovery.ServiceCombServerList
eureka:
  instance:
    leaseRenewalIntervalInSeconds: '10'
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/
