swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.huawei.demo4mt.CodeFirstSpringmvcServer"
  x-java-interface: "com.huawei.demo4mt.CodeFirstSpringmvcIntf"
basePath: "/codeFirstSpringmvc"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /responseEntity:
    post:
      operationId: "responseEntity"
      produces:
      - "text/plain"
      parameters:
      - in: "body"
        name: "strBody"
        required: false
        schema:
          type: "string"
      - name: "date"
        in: "formData"
        required: false
        type: "string"
        format: "date-time"
      responses:
        200:
          description: "response of 200"
          schema:
            type: "string"
          headers:
            h1:
              type: "string"
            h2:
              type: "string"